### ISSUE TITLE
Notification system

### ISSUE THREAD

**Issue by binarycleric** [colindean/plas#10]
Displays to a user or emails them when they've received a ticket or there's a new event, tournament, etc.

**Comment by colindean** [comment]
A candidate for this is [Extra! Extra!](http://github.com/steveklabnik/extraextra), but it might not handle the emails we'd want for certain cases.

**Comment by colindean** [comment]
It's also important to note that not all installations will have Internet access, so it's important to enable the admin to disable email notifications.
