### ISSUE TITLE
Tournament Management System

### ISSUE THREAD

**Issue by binarycleric** [colindean/plas#11]
Possibly using [Challonge! API](http://challonge.com/api)

**Comment by colindean** [comment]
Thoughts:
1. Initially use Challonge as the only backend, but its model is a subclass of a greater Tournament class/interface.
2. Eventually implement a self-contained tournament management system for folks who don't want to use Challonge. Given Challonge's successful use at Pittco, this contribution would likely come from someone who didn't want to use Challonge (e.g., not me).

ChallongeTournament < Tournament
PLASTournament < Tournament

Tournament will likely follow Challonge's API--it just makes sense.

**Comment by colindean** [comment]
Two types of tournaments:
1. Team Tournament - add Users to team, or hide teams - good for N vs N matches
2. Individual Tournament - Users are the team - good for 1 vs 1 or FFA matches

Teams can live for as long as a tournament, or teams can be used across multiple tournaments. This can create an Olympics type thing.

**Comment by colindean** [comment]
There are two types of tournaments now: PLASTournament and Challonge::Tournament. The former is for simple, boiloff tournaments with no need for score tracking -- just a winner. Challonge tournaments are for everything else.

**Comment by colindean** [comment]
I'm having considerable problems implementing this using Rails' polymorphic associations.

http://stackoverflow.com/questions/8440711/how-can-i-build-a-complex-polymorphic-association-which-includes-activeresource

**Comment by colindean** [comment]
I'm going to unhook the PLASTournament stuff and just go with Challonge for everything for now.
