### ISSUE TITLE
Shoutbox System 

### ISSUE THREAD

**Issue by binarycleric** [colindean/plas#14]
Require features in initial implementation:
1. Admin permissions to moderate (delete posts, ban users, _no editing_)
2. Automatically linkify links

Nice to have features, may be filed as Enhancements if not in initial implementation:
1. Profanity filter (really, just a filter) - Must be configurable and have "good defaults"
2. URL shortening for links using bit.ly or some locally-hostable product - Mad props for implementing shortening in PLAS
3. Upvote/downvote or agree/disagree buttons (anonymous)
4. Markdown syntax accepted

This would be a great project for someone just getting their feet wet in Rails.

**Comment by colindean** [comment]
I think binarycleric is going to attack this as a good intro to Rails development.

Ensure you write unit tests, too.

**Comment by colindean** [comment]
This is a good quickie!

**Comment by colindean** [comment]
Doing this with apotomo...
