### ISSUE TITLE
Header looks terrible in some browsers

### ISSUE THREAD

**Issue by colindean** [colindean/plas#22]
It's not blueish, and the lower nav is half on top of the subtitle. The body contents are pushed up, as well. 

This [screenshot](http://twitpic.com/37t60u/full) shows it well.

**Comment by colindean** [comment]
this also affects safari on iOS. see the ![ipad screenshot](http://i.imgur.com/0EZUp.png).

**Comment by colindean** [comment]
Now that Firefox 4 is out, I'm even less concerned with this. If by the time PLAS is ready for release, this is still not looking right in iOS Safari, we'll attack it.

**Comment by colindean** [comment]
This is affecting Opera 11.01 now, too.

![screenshot](http://i.imgur.com/4LTrp.png)

**Comment by colindean** [comment]
Gradients are not supported in Opera until 11.10. I'll update to that and check it out. I expect the gradients to work, but the structure may still be wonky.

**Comment by colindean** [comment]
Upgraded to the latest Opera -- fixed.

Could someone test this on an iPhone/iPad and some of the Android tablet browsers? WFFM on stock Android browser.

**Comment by shawnwall** [comment]
looking ok to me
![looking ok to me](http://i.imgur.com/dIDp4.png)

**Comment by colindean** [comment]
w00t! Closing. Thanks, @shawnwall.
