### ISSUE TITLE
Creating admin user results in error page

### ISSUE THREAD

**Issue by arielkirkwood** [colindean/plas#42]
Hello again,

Now that I have the app running, I am running into an issue when signing up (presumably for the admin account, but I'm not sure).

Navigating to localhost:3000, I'm presented with the splash page, and clicking around on any of the navigation links work (though I obviously don't have any users or events yet). When I click sign up, I get the signup page to load correctly, but once I enter my information, I am presented with [the following error text](https://gist.github.com/999833).

The error seems to be "Permission code payments.accept does not exist".

Thanks in advance for any help!

**Comment by arielkirkwood** [comment]
Hmm, so I found that /godmode worked, regardless of the errors occurring.

**Comment by colindean** [comment]
Did you run `rake db:migrate`? That permission should have been created. 

## Could you file another issue saying that permission lookups should fail closed gracefully but log the warning.

Colin Dean 

neonelectro reply@reply.github.com wrote:

Hello again, Now that I have the app running, I am running into an issue when signing up (presumably for the admin account, but I'm not sure). Navigating to localhost:3000, I'm presented with the splash page, and clicking around on any of the navigation links work (though I obviously don't have any users or events yet). When I click sign up, I get the signup page to load correctly, but once I enter my information, I am presented with [the following error text](https://gist.github.com/999833). The error seems to be "Permission code payments.accept does not exist". Thanks in advance for any help! -- Reply to this email directly or view it on GitHub: https://github.com/colindean/plas/issues/42

**Comment by colindean** [comment]
Once you were in godmode, did you check the Permissions and see if it does in fact exist? Maybe there's a typo somewhere.

**Comment by arielkirkwood** [comment]
Sorry about the lack of feedback, but just letting you know your latest commits fixed the problem for me.

**Comment by colindean** [comment]
Great!
