### ISSUE TITLE
Event creation and management

### ISSUE THREAD

**Issue by binarycleric** [colindean/plas#7]
Administrative users should be able to create and manage events. Events have a location, start/end datetime, and a name.

**Comment by colindean** [comment]
Much of this is progressing in tandem with #8. Given that the Event class is a very, very central fixture of the entire workings of the application, this issue is likely to be closed one a base feature set and view are complete, and the constantly improved as necessary.

**Comment by colindean** [comment]
Closing this, as the base event management components are completed.
