### ISSUE TITLE
Ticketing System

### ISSUE THREAD

**Issue by binarycleric** [colindean/plas#8]
- Create master tickets for purchase per event
- Tickets can come in packs of N for $M per ticket
- Use PayPal or allow for mailed checks or pre-registered walk-in payments
- Tickets are never deleted, can be transferred between events (although that will likely never be done)
- User can purchase N tickets
- User can assign tickets to other folks

**Comment by colindean** [comment]
Commit 4b8f3a2c601bb380cab30c879c075ff487ca922f addresses ticket creation, PayPal integration, and purchasing N tickets.

TODO:
1. Mailed checks
2. Preregistered walk-ins
3. Ticket transfer

**Comment by colindean** [comment]
Mailed checks and preregistered walk-ins are considered _offline payments_.

I think that for now the workflow will be like this:
1. Offline payment user (OPU) registers an account.
2. OPU users "buy" a ticket and choose offline payment as their method, and to them they're good until later.
3. The registration is created, but not marked as paid.
4. A user who can `payments.accept` can view a user's registrations and mark the applicable one as paid.
5. OPU can then act as any other paid user.

In the event that the user bought a ticket package, we simply loop through all the generated registrations and mark them as paid.

If the user is a walk-in, we have them sign up if they haven't and choose offline payment.

**Comment by colindean** [comment]
The OPU interaction is done and has been done for a while. The implementation I did whenever I did it was to set the price paid to the original purchase amount, and then just not set the user of the ticket or create a transaction for it. Lack of a transaction is the best to show that it's not paid and Registration#paid? reflects that.

At step 4 in the prior comment, the payment-accepting user will record the information for the transaction and save it, the PLAS will associate the transaction with the registration and the registration will thus become paid.

**Comment by colindean** [comment]
Offline payments are recorded, but not validated (e.g. ensuring we got enough money) as of 85c7f62067cfceae1f76. There is no provision for having multiple transactions to accomodate a single registration. I don't think it's necessary.

I need to:
1. Validate transaction input (it's admin user, so we don't really have to validate for nastiness, just business logic)
2. Handle ticket transfer.

**Comment by colindean** [comment]
I've decided against validating transaction input for now, thus closing #16. I've filed another issue for the purpose of eventually doing validations of tracking data (#41).

**Comment by colindean** [comment]
There's just a little polishing left to do here.
